version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-edzoterem
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: edzoteremdb
      MYSQL_USER: edzouser
      MYSQL_PASSWORD: edzopass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: spring-edzoterem
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/edzoteremdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: edzouser
      SPRING_DATASOURCE_PASSWORD: edzopass

volumes:
  mysql-data: